name: build

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  directories: # Job that list subdirectories
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }} # generate output name dir by using inner step output
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs # Give it an id to handle to get step outputs in the outputs key above
        run: echo "::set-output name=dir::$(ls -d */ | jq -R -s -c 'split("\n")[:-1]')"
        # Define step output named dir base on ls command transformed to JSON thanks to jq
  loop:
    runs-on: ubuntu-latest
    needs: [directories] # Depends on previous job
    strategy:
      matrix:
        dir: ${{fromJson(needs.directories.outputs.dir)}} # List matrix strategy from directories dynamically
    steps:
      - uses: actions/checkout@v2
      # only install and run tests if they exist on folder
      - name: Build and run Jest tests
        run: cd ${{matrix.dir}} && if ls ./src/*spec* &>/dev/null ; then npm i && npm run test; else echo "No Jest tests found. Skipping..." ; fi
      # TODO: Make python tests work, for now they break because is not possible to mock Web3
      - name: Build and run PyTest tests
        run: cd ${{matrix.dir}} && if ls ./src/*test* &>/dev/null ; then echo "Tests without secret not supported yet, run locally -> npm i && npm run test"; else echo "No PyTest tests found. Skipping..." ; fi
